Repository compsy/u-can-act, pull requests merged in 2020-06, with the labels that each got.

#1568 Added squash questionnaire
  projects/sport-data-valley/seeds/protocols/squash.rb
  projects/sport-data-valley/seeds/questionnaires/squash.rb
Labels: LGTM, Set to merge...

#1592 Use word wrap
  app/assets/stylesheets/questionnaire.scss
Labels: LGTM, Set to merge...

#1559 Update ouders_dagboek.rb
  projects/ikia/seeds/questionnaires/ouders/ouders_dagboek.rb
Labels: minor changes

#1555 Update jongeren_dagboek.rb
  projects/ikia/seeds/questionnaires/jongeren/jongeren_dagboek.rb
Labels: minor changes

#1603 Update all gems
  Gemfile
  Gemfile.lock
  spec/controllers/questionnaire_controller_spec.rb
  spec/support/tasks.rb
Labels: LGTM, Set to merge...

#1622 Added otr to squash
  projects/sport-data-valley/seeds/protocols/squash.rb
Labels: LGTM

#1606 UCF project configuration + schedule questionnaires on a specific day + prioritize questionnaire responses
  app/controllers/questionnaire_controller.rb
  app/models/invitation_token.rb
  app/models/measurement.rb
  app/models/person.rb
  app/models/response.rb
  app/use_cases/reschedule_responses.rb
  db/migrate/20200616124000_add_open_from_day_to_measurement.rb
  db/migrate/20200616134711_add_priority_to_measurement.rb
  db/schema.rb
  projects/u-can-feel/assets/images/logo.png
  projects/u-can-feel/assets/images/logo_mentor.png
  projects/u-can-feel/assets/images/logo_student.png
  projects/u-can-feel/assets/stylesheets/project.scss
  projects/u-can-feel/config/settings.yml
  projects/u-can-feel/seeds/organizations/ucf.rb
  projects/u-can-feel/seeds/protocols/cohort_study.rb
  projects/u-can-feel/seeds/protocols/diary_study.rb
  projects/u-can-feel/seeds/questionnaires/demografie.rb
  projects/u-can-feel/seeds/questionnaires/informed_consent.rb
  projects/u-can-feel/seeds/questionnaires/other_factors.rb
  projects/u-can-feel/seeds/questionnaires/school.rb
  projects/u-can-feel/seeds/questionnaires/socialnetworks.rb
  projects/u-can-feel/seeds/questionnaires/weekly_diary.rb
  projects/u-can-feel/seeds/questionnaires/wellbeing.rb
  projects/u-can-feel/seeds/seeds.rb
  projects/u-can-feel/seeds/teams/ucf.rb
  spec/models/invitation_token_spec.rb
  spec/models/measurement_spec.rb
  spec/models/person_spec.rb
  spec/models/questionnaire_spec.rb
  spec/models/response_spec.rb
  spec/use_cases/calculate_distribution_spec.rb
  spec/use_cases/recalculate_scores_spec.rb
  spec/use_cases/update_distribution_spec.rb
Labels: LGTM
