Repository compsy/u-can-act, pull requests merged in 2021-06, with the labels that each got.

#2005 Add ostrc-o questionnaire
  app/assets/javascripts/questionnaire_logic.js.erb
  app/models/measurement.rb
  projects/sport-data-valley/seeds/protocols/daily_protocol.rb
  projects/sport-data-valley/seeds/protocols/ostrc_h.rb
  projects/sport-data-valley/seeds/protocols/ostrc_o.rb
  projects/sport-data-valley/seeds/protocols/ostrc_o_h.rb
  projects/sport-data-valley/seeds/questionnaires/ostrc_h.rb
  projects/sport-data-valley/seeds/questionnaires/ostrc_o.rb
  projects/sport-data-valley/seeds/seeds.rb
Labels: Review requested

#2010 Leave the questionnaire key intact so we can translate it in the backend
  app/serializers/api/protocol_subscription_serializer.rb
  spec/serializers/api/protocol_subscription_serializer_spec.rb
Labels: 1 minute review

#1927 [38707427] Added squash onetime response
  projects/sport-data-valley/seeds/protocols/squash_otr.rb
  projects/sport-data-valley/seeds/seeds.rb
Labels: LGTM
